### ISSUE TITLE
Разработка базовых требований ios-приложения.

### ISSUE THREAD

**Issue by romikabi** [TramIncorporated/tram-ios#1]
Необходимо систематизировать требования к первой версии ios-приложения.

**Comment by romikabi** [comment]
Окна:
* Профиль 
> <img src="https://user-images.githubusercontent.com/26742317/32688552-f9e0bf04-c6e3-11e7-926c-a58d7e97cc78.png" width="200">
* Поиск;
* Список вышедшего/предстоящего с отметочками;

Функции:
* Поиск медиа;
* Просмотр страниц медиа;
* Добавление в списки "буду смотреть", "смотрю" (для сериалов), "смотрел(а)";
* Отображение медиа из списков на отдельной странице с возможностью отмечать просмотренное;
* Отображение статистики в профиле;

Тонкости:
* Инкапсуляция взаимодействия с сервером;

**Comment by romikabi** [comment]
Предварительный список такой, по необходимости можно дописывать или переоткрыть issue.

**Comment by nicklyu** [comment]
По поводу 
**Добавление в списки "буду смотреть", "смотрю" (для сериалов), "смотрел(а)" 
Отображение медиа из списков на отдельной странице с возможностью отмечать просмотренное;
Отображение статистики в профиле;**

на первом этапе это будет храниться на устройстве, без синхронизации, я правильно понимаю?
логику взаимодействий с сервером на данные задачи предусматривать пока не нужно?

**Comment by romikabi** [comment]
@nicklyu нужно подумать, удобнее и проще ли это хранить на устройстве. Если да, то предусматривать не нужно.

**Comment by nicklyu** [comment]
@romikabi на первое время давай на устройствах, введение системы аккаунтов и авторизации это много для первого спринта
