### ISSUE TITLE
Разработать mock-ups страниц приложения.

### ISSUE THREAD

**Issue by romikabi** [TramIncorporated/tram-ios#3]
- [x] watchlist
- [x] movie view
- [x] profile
- [x] search

**Comment by crowleash** [comment]
watchlist
<img src="https://user-images.githubusercontent.com/32108676/33088757-99f0cfb6-ceff-11e7-8528-70afea931cb8.png" width=200>

**Comment by crowleash** [comment]
Movie view
<img src="https://user-images.githubusercontent.com/32108676/33088805-c869a264-ceff-11e7-8490-f885f881324d.png" width=200>
<img src="https://user-images.githubusercontent.com/32108676/33088842-e76c0bde-ceff-11e7-98e5-b732fbba1530.png" width=200>
<img src="https://user-images.githubusercontent.com/32108676/33088874-fccd7f3a-ceff-11e7-81aa-b0bb19369a01.png" width=200>

**Comment by crowleash** [comment]
Search view
<img src="https://user-images.githubusercontent.com/32108676/33088927-2782feee-cf00-11e7-8186-d776f333f8bd.png" width=200>
<img src="https://user-images.githubusercontent.com/32108676/33088954-45fa859a-cf00-11e7-81c1-722945a7b5ba.png" width=200>

**Comment by crowleash** [comment]
profile view
<img src="https://user-images.githubusercontent.com/32108676/33832437-345a99b4-de8d-11e7-81d1-0f5107499809.jpg" width=200>
<img src="https://user-images.githubusercontent.com/32108676/33832439-376708d6-de8d-11e7-8031-11148032e6c4.png" width=200>
